import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import CreateExperience from "~/components/CreateExperience";
import CreateExperienceForm from "~/components/CreateExperience/CreateExperienceForm";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>Create a New Experience</div>
        <Link href={"/experience/create/hello-world"}>
          Create an Experience
        </Link>
      </main>
    </>
  );
};

export default Home;
